spring:
  profiles:
    active: loc
---

server:
  port: 8080

spring:
  profiles: loc
  datasource:
    #driver-class-name: org.mariadb.jdbc.Driver
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mariadb://localhost:3306/ojt
    username: root
    password: real3817
    tomcat:
      validation-query: select 1
      validation-interval: 300000
      test-while-idle: true
      time-between-eviction-runs-millis: 300000
      min-evictable-idle-time-millis: 300000
      min-idle: 10
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix:  .jsp
  http:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      
mybatis:
  mapper-locations:
  - classpath:com/barunsw/simple/**/*Mapper.xml
  config-location: classpath:mybatis-config.xml
  
logging:
  level:
    org.springframework.security: WARN
    org.springframework.web: DEBUG
    org.springframework.core: INFO
    org.springframework.beans: INFO
    org.springframework.context: INFO
    org.springframework.boot: INFO
  config: classpath:log4j2.xml
  